{{-- START: CONTENT OF CHAPTER 6 --}}

{{--<!doctype html>--}}
{{--<html lang="en">--}}
{{--<head>--}}
{{--    <meta charset="UTF-8">--}}
{{--    <meta name="viewport"--}}
{{--          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">--}}
{{--    <meta http-equiv="X-UA-Compatible" content="ie=edge">--}}
{{--    <title>Contact Page</title>--}}
{{--</head>--}}
{{--<body>--}}
{{--    <h1>Contact Page</h1>--}}

{{--</body>--}}
{{--</html>--}}

{{--END: CONTENT OF CHAPTER 6--}}

{{--CHAPTER 7--}}
{{-- file app trong thư mục layouts --}}

{{--Khai báo áp dụng Template app trong thư mục layouts--}}
@extends('layouts.app')

{{-- Với các nội dung tương ứng - sẽ gắn vào Template như sau --}}
@section('content')
    {{--  include nội dung các trang khác vào  --}}
    {{--@include();--}}

    <h1>Contact Page</h1>
    <p>The list below was generated by Laravel View and Blade Template</p>
    <ul>
    @if(count($people))
        @foreach($people as $person)
            <li>{{$person}}</li>
        @endforeach
    @endif
    </ul>

@endsection {{-- hoặc có thể dùng stop--}}


{{-- Comment phần sau để tắt JavaScript Alert --}}
{{--@section('footer')--}}
{{--    <h1>Footer</h1>--}}
{{--    <script>alert('Alert created in footer section')</script>--}}
{{--@endsection()--}}
{{-- hoặc có thể dùng stop--}}
